namespace BudgetPlan.Contracts.ControllerContracts.SettlementPeriods.GetSettlementPeriods;

public sealed record GetSettlementPeriodsResponse(IReadOnlyList<SettlementPeriodResponse> SettlementPeriods);
